<a href="https://colab.research.google.com/github/Jeeeeeeeee/Study/blob/main/%5BPytorch_01%5D_%EA%B8%B0%EB%B3%B8%ED%95%A8%EC%88%98_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%88%EB%9F%AC%EC%98%A4%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Torch / Tensor

In [ ]:
import torch
import numpy as np

In [ ]:
x = torch.empty(5,4)
print(x)

tensor([[-9.2314e+33,  3.0840e-41,  7.0065e-44,  6.8664e-44],
        [ 6.3058e-44,  6.7262e-44,  7.8473e-44,  6.3058e-44],
        [ 7.0065e-44,  7.2868e-44,  1.1771e-43,  6.7262e-44],
        [ 6.8664e-44,  8.1275e-44,  7.2868e-44,  7.2868e-44],
        [ 8.1275e-44,  6.7262e-44,  7.4269e-44,  6.4460e-44]])


In [ ]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.zeros(2)

tensor([0., 0.])

In [ ]:
torch.rand(5,6)

tensor([[0.4301, 0.2741, 0.2613, 0.1297, 0.9968, 0.1168],
        [0.1762, 0.4423, 0.2403, 0.5170, 0.3318, 0.9365],
        [0.4295, 0.4874, 0.8196, 0.9137, 0.0780, 0.9195],
        [0.7639, 0.5790, 0.6971, 0.1672, 0.8388, 0.5286],
        [0.9628, 0.7492, 0.0693, 0.3459, 0.6010, 0.6195]])

In [ ]:
l = [13, 4]
r = np.array([4, 56, 7]) 

# list나 array로 되어 있으면 tensor로 바꿔줘야합니다.

In [ ]:
torch.tensor(l)

tensor([13,  4])

In [ ]:
torch.tensor(r)

tensor([ 4, 56,  7])

In [ ]:
# 사이즈 확인
x.size()

torch.Size([5, 4])

In [ ]:
type(x)

torch.Tensor

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(x)
print(y)

tensor([[0.4889, 0.2516],
        [0.2356, 0.5798]])
tensor([[0.1619, 0.3249],
        [0.8529, 0.6841]])


In [ ]:
print(x+y)
print(torch.add(x,y))

tensor([[0.6508, 0.5765],
        [1.0884, 1.2639]])
tensor([[0.6508, 0.5765],
        [1.0884, 1.2639]])


In [ ]:
y.add(x)

tensor([[1.1397, 0.8281],
        [1.3240, 1.8437]])

In [ ]:
y

tensor([[0.6508, 0.5765],
        [1.0884, 1.2639]])

In [ ]:
y.add_(x)
# _를 넣어주면 inplace -> y에 x를 넣어서 y를 대신한다.

tensor([[1.1397, 0.8281],
        [1.3240, 1.8437]])

In [ ]:
y # 그래서 y가 바뀌어있다.

tensor([[1.1397, 0.8281],
        [1.3240, 1.8437]])

In [ ]:
y[1,1] # 1행 1열

tensor(1.8437)

In [ ]:
y[:, 1]

tensor([0.8281, 1.8437])

In [ ]:
# view 함수 -> 사이즈를 자유롭게 바꿔줄 수 있다.

x = torch.rand(8,8)
print(x)

tensor([[0.7132, 0.7099, 0.1952, 0.5424, 0.1156, 0.0904, 0.1458, 0.4447],
        [0.5022, 0.3818, 0.0753, 0.4596, 0.1301, 0.2926, 0.2619, 0.9827],
        [0.4766, 0.1041, 0.8072, 0.3585, 0.5567, 0.6800, 0.1132, 0.7139],
        [0.6712, 0.1297, 0.0141, 0.5364, 0.5082, 0.8289, 0.6395, 0.4330],
        [0.5812, 0.5240, 0.6789, 0.6718, 0.2540, 0.7784, 0.6737, 0.7228],
        [0.5543, 0.0322, 0.2613, 0.8569, 0.7168, 0.6699, 0.9896, 0.7602],
        [0.7060, 0.3893, 0.7684, 0.3274, 0.6006, 0.8840, 0.4101, 0.1233],
        [0.3469, 0.8662, 0.6939, 0.3821, 0.4065, 0.4186, 0.7537, 0.2914]])


In [ ]:
x.view(64) # 한줄로 만들어주겠다 ..^^

tensor([0.7132, 0.7099, 0.1952, 0.5424, 0.1156, 0.0904, 0.1458, 0.4447, 0.5022,
        0.3818, 0.0753, 0.4596, 0.1301, 0.2926, 0.2619, 0.9827, 0.4766, 0.1041,
        0.8072, 0.3585, 0.5567, 0.6800, 0.1132, 0.7139, 0.6712, 0.1297, 0.0141,
        0.5364, 0.5082, 0.8289, 0.6395, 0.4330, 0.5812, 0.5240, 0.6789, 0.6718,
        0.2540, 0.7784, 0.6737, 0.7228, 0.5543, 0.0322, 0.2613, 0.8569, 0.7168,
        0.6699, 0.9896, 0.7602, 0.7060, 0.3893, 0.7684, 0.3274, 0.6006, 0.8840,
        0.4101, 0.1233, 0.3469, 0.8662, 0.6939, 0.3821, 0.4065, 0.4186, 0.7537,
        0.2914])

In [ ]:
x.view(4, 16) # 4*16의 행렬로 변환할 수 있다.

tensor([[0.7132, 0.7099, 0.1952, 0.5424, 0.1156, 0.0904, 0.1458, 0.4447, 0.5022,
         0.3818, 0.0753, 0.4596, 0.1301, 0.2926, 0.2619, 0.9827],
        [0.4766, 0.1041, 0.8072, 0.3585, 0.5567, 0.6800, 0.1132, 0.7139, 0.6712,
         0.1297, 0.0141, 0.5364, 0.5082, 0.8289, 0.6395, 0.4330],
        [0.5812, 0.5240, 0.6789, 0.6718, 0.2540, 0.7784, 0.6737, 0.7228, 0.5543,
         0.0322, 0.2613, 0.8569, 0.7168, 0.6699, 0.9896, 0.7602],
        [0.7060, 0.3893, 0.7684, 0.3274, 0.6006, 0.8840, 0.4101, 0.1233, 0.3469,
         0.8662, 0.6939, 0.3821, 0.4065, 0.4186, 0.7537, 0.2914]])

In [ ]:
x.view(-1, 16) # -1을 넣어주면 결국 64 만들기 위해서 자기가 알아서 게산한다긔
# cnn인 경우에 conv -> fc layer로 넘어갈 때 정사각형 이미지를 일렬로 펴줄 때 사용한다.

tensor([[0.7132, 0.7099, 0.1952, 0.5424, 0.1156, 0.0904, 0.1458, 0.4447, 0.5022,
         0.3818, 0.0753, 0.4596, 0.1301, 0.2926, 0.2619, 0.9827],
        [0.4766, 0.1041, 0.8072, 0.3585, 0.5567, 0.6800, 0.1132, 0.7139, 0.6712,
         0.1297, 0.0141, 0.5364, 0.5082, 0.8289, 0.6395, 0.4330],
        [0.5812, 0.5240, 0.6789, 0.6718, 0.2540, 0.7784, 0.6737, 0.7228, 0.5543,
         0.0322, 0.2613, 0.8569, 0.7168, 0.6699, 0.9896, 0.7602],
        [0.7060, 0.3893, 0.7684, 0.3274, 0.6006, 0.8840, 0.4101, 0.1233, 0.3469,
         0.8662, 0.6939, 0.3821, 0.4065, 0.4186, 0.7537, 0.2914]])

In [ ]:
# tensor에서 numpy로 넘어가기
y = x.numpy()
print(y) 

[[0.7131503  0.70990765 0.19518661 0.54244804 0.11561865 0.09044588
  0.14584595 0.4447133 ]
 [0.5022121  0.38176453 0.07525802 0.45959777 0.13011438 0.29264212
  0.26191175 0.9827154 ]
 [0.47662246 0.10409927 0.8071862  0.35849953 0.5566648  0.6799857
  0.11323869 0.71387714]
 [0.67124665 0.12966388 0.01408136 0.5364081  0.50818074 0.8289325
  0.6395027  0.4330234 ]
 [0.5811778  0.5240132  0.67891777 0.6717996  0.25404096 0.7784378
  0.6736847  0.7227898 ]
 [0.554295   0.03221619 0.2613023  0.85688525 0.71680975 0.6698792
  0.989569   0.76017714]
 [0.7060319  0.389265   0.7683992  0.32737094 0.6006412  0.8839755
  0.41008854 0.12329131]
 [0.34693313 0.8662183  0.6938842  0.38212234 0.40653855 0.41860914
  0.7537241  0.29137248]]


In [ ]:
type(y)

numpy.ndarray

In [ ]:
# item() 메소드는 tensor가 scholar일 때만 사용 가능하다 (원소가 1개일 때)

x = torch.ones(1)
print(x)

tensor([1.])


In [ ]:
x.item() # x안의 값을 뽑아내는 방법 -> loss function 계산할 때 loss값이 하나만 나오니까..
# floating 할 때나 볼 때 사용하기 때문에 자주 쓸 수 있다.

1.0

# Data Load

1. 파이토치 제공 데이터 사용할 때 
2. 같은 클래스 별 폴더 이미지 데이터 사용할 때
3. 개인 데이터 사용할 때 (2 types)

In [ ]:
import torch 
import torchvision
import torchvision.transforms as tr # 데이터를 불러오면서 바로 전처리할 수 있게 해주는 lib
from torch.utils.data import DataLoader, Dataset # dataloader는 batchsize 형태로 만들어서 실제로 학습할 때 이용할 수 있는 형태를 만들어주는 lib
# dataset은 tuning할 때 사용한다.
import numpy as np

In [ ]:
transform = tr.Compose([tr.Resize(8), tr.ToTensor()])
# (8, 8)로 resize하고 tensor data로 바꿔주는 작업

# Transforms on PIL Image -> 처음에 들어오는 데미지는 PIL form으로 들어옴. 이거 아니면 오류남.
# Pad, Grayscale, RandomCrop, Normalize 등 다양한 전처리 작업 방법이 있으니 직접 찾아보고 할 것!

In [ ]:
trainset = torchvision.datasets.CIFAR10(root = './data', train = True, download  = True, transform = transform)
testset = torchvision.datasets.CIFAR10(root = './data', train = False, download = True, transform = transform)
# transform은 다운로드 받고 들어오는 애들에 대해서 전처리를 해주겠다.

  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified


In [ ]:
trainset[0][0].size() # 이 형태를 잘 봐야한다. (채널 수, 이미지 크기)

torch.Size([3, 8, 8])

In [ ]:
trainloader = DataLoader(trainset, batch_size = 50, shuffle = True, num_workers = 2)
testloader = DataLoader(testset, batch_size = 50, shuffle = True, num_workers= 2)

# num_workers -> 데이터를 load할 때 sub process 몇개 쓸래? 에러나면 0으로 놔도 상관 X
# 여기까지만 하면 batch 형태로 알아서 분류해놔서 바로 모델 돌릴 수 있다.

In [ ]:
len(trainloader)

# 데이터 갯수 5만개, batch size 50, 따라서 batch(50개)짜리가 천개 있슴당
# 5만개를 잘 나누었다!

1000

In [ ]:
# 실제 값을 보고 싶을 땐?

dataiter = iter(trainloader)
images, labels = dataiter.next() # 하나씩 불러올게

In [ ]:
images.size() 
# torch.Size([50, 3, 8, 8]) -> batch size 50, 채널수 3개, 크기(너비8*높이8)

torch.Size([50, 3, 8, 8])

### 개인 데이터를 사용할 때 
1) 같은 클래스 별 폴더 이미지 데이터를 사용

In [ ]:
# ./class/tiger  ./class/lion

transform = tr.Compose([tr.Resize(16), tr.ToTensor()])
trainset = torchvision.datasets.ImageFolder(root = './class', transform = transform)
# class 안에 있는 image들을 알아서 search해준다. 각각의 폴더에 대해 알아서 labeling 매겨준다. 게다가 전처리까지 된다!
trainloader = DataLoader(trainset, batch_size = 50, shuffle = True, num_workers = 2)
print(len(trainloader()))

2) 개인 데이터 사용 (2 types)

In [ ]:
train_images = np.random.randint(256, size = (20, 32, 32, 3))
train_labels = np.random.randint(2, size = (20, 1))

# preprocessing... 전처리를 먼저 하면 더 좋다.
# train_images, train_labels = preprocessing(train_images, train_labels)

print(train_images.shape, train_labels.shape)

# 데이터 이따구로 들어와 있다고 가정합시다. 

(20, 32, 32, 3) (20, 1)


In [ ]:
# 그리고 본 양식을 기억해 두어야 한다!

class TensorData(Dataset): # 아까 받아온 Dataset을 상속받을 class 만들어주기...

  def __init__(self, x_data, y_data): 
    self.x_data = torch.FloatTensor(x_data) # x_data가 tensor로 바뀌게 만들어줌.
    self.x_data = self.x_data.permute(0,3,1,2) # 이미지 개수, 채널 수, 이미지 너비, 높이
    # permute 함수를 이용해서 순서를 바꿔주는 것 size 찍어서 위에꺼랑 확인해봐야한다.
    self.y_data = torch.LongTensor(y_data)
    # tensor 종류 여러개.. 그냥일수도 있고 float long 정할 수도 있다.
    self.len = self.y_data.shape[0]

  def __getitem__(self, index): # x, y를 튜플 형태로 내보내게 한다.
    return self.x_data[index], self.y_data[index]

  def __len__(self):
    return self.len

In [ ]:
train_data = TensorData(train_images, train_labels)
train_lodaer = DataLoader(train_data, batch_size = 10, shuffle = True)

In [ ]:
train_data[0][0].size()

torch.Size([3, 32, 32])

In [ ]:
dataiter = iter(train_lodaer)
images, labels = dataiter.next()

In [ ]:
images.size()

torch.Size([10, 3, 32, 32])

개인 데이터 + transform

In [ ]:
# 이게 기본 양식.. 나머지는 원하는대로 작업

from torch.utils.data import Dataset

class MyDataset(Dataset):

  def __inint__(self):

  def __getitem__(self, index):

  def __len__(self):

In [74]:
from torch.utils.data import Dataset

class MyDataset(Dataset):

  def __init__(self, x_data, y_data, transform = None): # transform 디폴트 값 안주겠다는 떳..
    self.x_data = x_data
    self.y_data = y_data
    self.transform = transform # 뭔가 들어오면 그냥 그거 쓰셈.
    self.len = len(y_data)

  def __getitem__(self, index):
    sample = self.x_data[index], self.y_data[index]
    
    if self.transform:
      sample = self.transform(sample)
    
    return sample # transform이 있으므로 내보내 주기 전에 위에서 transform 전처리 작업을 하겠다.

  def __len__(self):
    return self.len


class ToTensor: # ToTensor -> 텐서를 바꿔주는 클래스 

  def __call__(self, sample): # call 함수
    inputs, labels = sample
    inputs = torch.FloatTensor(inputs) # input은 float
    inputs = inputs.permute(2,0,1) # 이미지 사이즈 바꾸고
    return inputs, torch.LongTensor(labels) # 나갈 때 tensor



class LinearTensor:

  def __init__(self, slope = 1, bias = 0):
      self.slope = slope
      self.bias = bias

  def __call__(self, sample):
      inputs, labels = sample
      inputs = self.slope*inputs + self.bias # slope랑 bias가 있어야 하므로.. 위에서 받아올 수 있게 init 지정해주어야 한다.
      return inputs, labels
  

In [75]:
trans = tr.Compose([ToTensor(), LinearTensor(2,5)]) # slope 2 bias 5
ds1 = MyDataset(train_images, train_labels, transform = trans)
train_loader1 = DataLoader(ds1, batch_size = 10, shuffle = True)

In [77]:
images

tensor([[[[163., 218., 105.,  ...,  35., 201., 121.],
          [235., 176., 250.,  ...,  97., 221., 131.],
          [149.,  15.,  11.,  ..., 185.,  45., 140.],
          ...,
          [133.,  88.,  34.,  ...,  50., 194.,  20.],
          [108., 255.,  40.,  ...,  98., 105., 100.],
          [204.,  62., 107.,  ...,  26., 241., 113.]],

         [[137., 237.,  17.,  ...,  30.,  33., 135.],
          [ 41., 217.,  77.,  ..., 208., 170., 122.],
          [ 63., 202., 204.,  ...,  30., 162.,   1.],
          ...,
          [ 57., 252., 213.,  ...,  56.,  11., 226.],
          [146., 155., 136.,  ...,  28.,  72., 207.],
          [135.,  10.,  98.,  ...,   1., 180.,  94.]],

         [[216., 113., 112.,  ..., 149., 152., 110.],
          [224., 130., 211.,  ..., 202., 125., 255.],
          [ 79.,  99., 230.,  ...,  53.,  87., 176.],
          ...,
          [ 91., 105., 133.,  ..., 215., 240., 199.],
          [191., 248.,  38.,  ..., 252., 225., 120.],
          [147.,  60.,  42.,  ...

In [65]:
# 위에서는 numpy형태로 받아왔기 때문에 tr.~를 사용할 수 없다 .
# 만약 쓰고 싶으면 아래의 MyTrnasform 함수를 사용하는 게 좋다!

class MyDataset(Dataset):
  
  def __init__(self, x_data, y_data, trainsform = None):

    self.x_data = x_data
    self.y_data = y_data
    self.transform = transform
    self.len = len(y_data)

  def __getitem__(self, index):
    sample = self.x_data[index], self.y_data[index]

    if self.transform:
      sample = self.transform(sample)

      return sample

  def __len__(self):
    return self.len


class MyTransform:

  def __call__(self, sample):
    inputs, labels = sample
    inputs = torch.FloatTensor(inputs)
    inputs = inputs.permute(2,0,1)
    labels = torch.FloatTensor(labels) # 일단 tensor로 만들어준다.

    transf = tr.Compose([tr.ToPILImage(), tr.Resize(120), tr.ToTensor(), tr.Normalize((0.5, 0.5, 0.5), (0.5,0.5,0.5))])
    # PILImage로 만들어주는 함수를 사용하고, Resize 하고 이것저것 할 수 있다.
    
    final_output = transf(inputs)

    return final_output, labels

In [78]:
ds2 = MyDataset(train_images, train_labels, transform = MyTransform())
train_loader2 = DataLoader(ds2, batch_size = 10, shuffle = True)

In [79]:
first_data = ds2[0]
features, labels = first_data
print(type(features), type(labels))

<class 'torch.Tensor'> <class 'torch.Tensor'>


In [80]:
dataiter2 = iter(train_loader2)
images2, labels2 = dataiter2.next()

In [81]:
images2.size()

torch.Size([10, 3, 120, 120])

In [82]:
images2

tensor([[[[ 0.9922,  0.9922,  0.7647,  ...,  0.7333,  0.7961,  0.7961],
          [ 0.9922,  0.9922,  0.7647,  ...,  0.7333,  0.7961,  0.7961],
          [ 0.8824,  0.8824,  0.6627,  ...,  0.6157,  0.6392,  0.6392],
          ...,
          [ 0.3961,  0.3961,  0.2392,  ...,  0.0745,  0.1765,  0.1765],
          [ 0.6000,  0.6000,  0.4039,  ...,  0.0196,  0.0902,  0.0902],
          [ 0.6000,  0.6000,  0.4039,  ...,  0.0196,  0.0902,  0.0902]],

         [[ 0.6392,  0.6392,  0.6863,  ..., -0.2000, -0.3882, -0.3882],
          [ 0.6392,  0.6392,  0.6863,  ..., -0.2000, -0.3882, -0.3882],
          [ 0.4510,  0.4510,  0.4824,  ..., -0.1373, -0.2784, -0.2784],
          ...,
          [ 0.4275,  0.4275,  0.4431,  ..., -0.6078, -0.8039, -0.8039],
          [ 0.6157,  0.6157,  0.6392,  ..., -0.6157, -0.7961, -0.7961],
          [ 0.6157,  0.6157,  0.6392,  ..., -0.6157, -0.7961, -0.7961]],

         [[-0.8039, -0.8039, -0.6549,  ..., -0.2627, -0.1686, -0.1686],
          [-0.8039, -0.8039, -

- reference : https://www.youtube.com/channel/UCt9jbjxLBawaSaEsGB87D6g

- Youtube 딥러닝호형 DL bro